
stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

# Build Jobs
# Build Job Template
.build_template: &build_template
  image: node:10.0.0
  stage: build
  before_script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - git clone https://github.com/HumanCellAtlas/humancellatlas.github.io
    - npm install npm@6.5.0 -g
    - npm -v
    - npm install gatsby-cli@2.4.13 --global
    - npm install
  artifacts:
      paths:
        - public
        - maintenance

# Develop Build
build_develop:
  <<: *build_template
  environment:
    name: develop
  script:
    - export GATSBY_EXPLORE_URL=https://dev.data.humancellatlas.org/explore/
    - export GATSBY_FILE_SUMMARY_API_URL=https://service.dev.explore.data.humancellatlas.org/repository/summary
    - export GATSBY_TERM_FACETS_API_URL=https://service.dev.explore.data.humancellatlas.org/repository/projects
    - export GATSBY_SYSTEM_HEALTH_CHECK_API_URL=https://service.dev.explore.data.humancellatlas.org/health
    - export GATSBY_GTM_ID=GTM-M2J5NTJ
    - export GATSBY_GTM_AUTH=9YN1zUWSooX9gvYK43KPlg
    - export GATSBY_ENV_NAME=env-6
    - gatsby build
  only:
    - develop


# Develop Build
build_ux-dev:
  <<: *build_template
  environment:
    name: ux-dev
  script:
    - export GATSBY_EXPLORE_URL=https://ux-dev.data.humancellatlas.org/explore/
    - export GATSBY_FILE_SUMMARY_API_URL=https://service.dev.explore.data.humancellatlas.org/repository/summary
    - export GATSBY_TERM_FACETS_API_URL=https://service.dev.explore.data.humancellatlas.org/repository/projects
    - export GATSBY_SYSTEM_HEALTH_CHECK_API_URL=https://status.dev.data.humancellatlas.org/service/dcp-health-check-dev
    - export GATSBY_GTM_ID=GTM-M2J5NTJ
    - export GATSBY_GTM_AUTH=V6JsS1EO6wZraCRRVvsrlw
    - export GATSBY_ENV_NAME=env-11
    - gatsby build
  only:
    - ux-dev

# Integration Build
build_integration:
  <<: *build_template
  environment:
    name: integration
  script:
    - export GATSBY_EXPLORE_URL=https://integration.data.humancellatlas.org/explore/
    - export GATSBY_FILE_SUMMARY_API_URL=https://service.integration.explore.data.humancellatlas.org/repository/summary
    - export GATSBY_TERM_FACETS_API_URL=https://service.integration.explore.data.humancellatlas.org/repository/projects
    - export GATSBY_SYSTEM_HEALTH_CHECK_API_URL=https://service.integration.explore.data.humancellatlas.org/health
    - export GATSBY_GTM_ID=GTM-M2J5NTJ
    - export GATSBY_GTM_AUTH=idWkz24fhkH__F0XXIBNGA
    - export GATSBY_ENV_NAME=env-8
    - gatsby build
  only:
    - integration

# Staging Build
build_staging:
  <<: *build_template
  environment:
    name: staging
  script:
    - export GATSBY_EXPLORE_URL=https://staging.data.humancellatlas.org/explore/
    - export GATSBY_FILE_SUMMARY_API_URL=https://service.staging.explore.data.humancellatlas.org/repository/summary
    - export GATSBY_TERM_FACETS_API_URL=https://service.staging.explore.data.humancellatlas.org/repository/projects
    - export GATSBY_GTM_ID=GTM-M2J5NTJ
    - export GATSBY_GTM_AUTH=CVR6RDnBikpJoyAEnybSBw
    - export GATSBY_ENV_NAME=env-10
    - gatsby build
  only:
    - staging

########################################
# Deploy Jobs
########################################


# Deploy Job Template
.deploy_template: &deploy_template
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli

# Dev Deploy
deploy_develop:
  <<: *deploy_template
  environment:
    name: develop
  script:
    - export BUCKET=s3://dev.data.humancellatlas.org/
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id EDQUW4UP25O4L --paths "/*"
  only:
    - develop
# Dev Deploy
deploy_ux-dev:
  <<: *deploy_template
  environment:
    name: ux-dev
  script:
    - export BUCKET=s3://ux-dev.data.humancellatlas.org/
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E3JWRFLK4O8V1L --paths "/*"
  only:
    - ux-dev
# Integration Deploy
deploy_integration:
  <<: *deploy_template
  environment:
    name: integration
  script:
    - export BUCKET=s3://integration.data.humancellatlas.org/
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E2MB44J9QEJOYP --paths "/*"
  only:
    - integration

# Staging Deploy
deploy_staging:
  <<: *deploy_template
  environment:
    name: staging
  script:
    - export BUCKET=s3://staging.data.humancellatlas.org/
    - if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=public/; fi
    - aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E38D6Y96QKYO6 --paths "/*"
  only:
    - staging
